MACHINES = {
  :node => {
    :box_name => "almalinux/8",
    :cpus => 1,
    :memory => 1024,
    :net => "10.0.88.",
  }
}

N = 2

Vagrant.configure("2") do |config|
  (1..N).each do |i|
    MACHINES.each do |boxname, boxconfig|
      boxname = "node-loop-#{i}"
      net = boxconfig[:net] + (10 + i.to_i).to_s
      config.vm.define boxname do |node|
        node.vm.box = boxconfig[:box_name]
        node.vm.hostname = boxname
        node.vm.synced_folder ".", "/vagrant"
        node.vm.network "private_network", ip:net
        node.vm.provider "virtualbox" do |v|
          v.cpus = boxconfig[:cpus]
          v.memory = boxconfig[:memory]
          v.name = boxname
        end
      end
    end
  end
end
