MACHINES = {
  :node => {
    :box_name => "centos/7",
    :cpus => 1,
    :memory => 1024,
  }
}

N = 2

Vagrant.configure("2") do |config|
  (1..N).each do |i|
    MACHINES.each do |boxname, boxconfig|
      boxname = boxname.to_s + "-#{i}"
      config.vm.define boxname do |node|
        node.vm.box = boxconfig[:box_name]
        node.vm.hostname = boxname
        node.vm.synced_folder ".", "/vagrant"
        node.vm.provider "virtualbox" do |v|
          v.cpus = boxconfig[:cpus]
          v.memory = boxconfig[:memory]
          v.name = boxname
        end
      end
    end
  end
end
