MACHINES = {
  :node => {
    :box_name => "almalinux/10",
    :cpus => 1,
    :memory => 2048,
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each() do |boxname, boxconfig|
    config.vm.define "forward" do |node|
      node.vm.box = boxconfig[:box_name]
      node.vm.network "forwarded_port", guest: 80, host: 1080, protocol: "tcp"
      node.vm.network "forwarded_port", guest: 53, host: 1053, protocol: "udp"
      node.vm.provider "virtualbox" do |v|
        v.name = "forward"
        v.cpus = boxconfig[:cpus]
        v.memory = boxconfig[:memory]
      end
    end
  end
end
