Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"
  config.vm.synced ".", "/vagrant"
  config.vm.provider "virtualbox" do |v|
    v.name = "custom-node"
    v.memory = 2048
    v.cpus = 1
    v.customize ["modifyvm", :id, "--graphicscontroller", "VMSVGA"]
  end
end
