MACHINES = {
  :node => {
    :box_name => "almalinux/10",
    :cpus => 1,
    :memory => 2048,
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define "ansible" do |node|
      node.vm.box = boxconfig[:box_name]
      node.vm.synced_folder ".", "/vagrant"
      node.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "main.yaml"
        ansible.install_mode = "pip"
      end
      node.vm.provider "virtualbox" do |v|
        v.name = "ansi"
        v.cpus = boxconfig[:cpus]
        v.memory = boxconfig[:memory]
#        v.check_guest_additions = false
      end
    end
  end
end
